version: '3.8'

services:
  app:
    container_name: my-app
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.rule=Host(`yehouda.com`)"
      - "traefik.http.routers.react.entrypoints=web"
      - "traefik.http.services.react.loadbalancer.server.port=3000"
    networks:
      - web

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ".:/etc/traefik"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.yehouda.com`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
            
  whoami:
    image: "traefik/whoami"
    container_name: "traefik-whoami"
    networks:
        - web
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.yehouda.com`)"
        - "traefik.http.routers.whoami.entrypoints=web"

networks:
  web:
    driver: bridge
