name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    needs: linter
    container:
      image: node:18-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build react app
        run: yarn build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: node:18-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build/

      - name: Install serve and curl
        run: |
          yarn global add serve
          apk add curl

      - name: Serve app and test
        run: |
          serve -S build &
          sleep 10
          curl http://localhost:3000 | grep "React App"

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: node:18-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn test